version: "3.9"

services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    container_name: django
    command: gunicorn --workers=5  -b 0.0.0.0:8001 hackathon2022.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8001"
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
