version: "3.9"

services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres