# Generated by Django 3.2.5 on 2022-07-22 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offensiveAdsFlagger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAd',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='The status of the add', max_length=10)),
                ('title', models.CharField(help_text='The name / title of the ad', max_length=200)),
                ('description', models.CharField(help_text='A short description of the add', max_length=500, null=True)),
                ('audio_file_name', models.CharField(help_text='Name of the audio file. This will be used as the key when storing in s3', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='time where we made stroed the transcription')),
            ],
            options={
                'db_table': 'audio_ads',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('contains_food', models.BooleanField(default=False, help_text='whether this contains food or not')),
                ('confidence', models.FloatField(help_text='confidence returned by the model')),
            ],
            options={
                'db_table': 'audio_transcriptions',
            },
        ),
        migrations.CreateModel(
            name='JoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offensiveAdsFlagger.audioad')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audioad',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offensiveAdsFlagger.transcription'),
        ),
    ]
